version: "3.7"
services:
  pocketbase:
    image: spectado/pocketbase:latest
    container_name: pocketbase_Lake
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - ./data:/pb_data
      - ./public:/pb_public
      - ./migrations:/pb_migrations
      - ./pb_hooks:/pb_hooks
